# Generated by Django 5.2.1 on 2025-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="area_boundary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ward/"),
        ),
    ]
