# Generated by Django 5.2.1 on 2025-07-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0002_alter_ward_area_boundary_alter_ward_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ward",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
