# Generated by Django 5.2.1 on 2025-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0003_alter_ward_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="town",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
