# Generated by Django 5.2.1 on 2025-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0004_alter_ward_town"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
