# Generated by Django 5.2.1 on 2025-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0005_alter_ward_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='town',
            new_name='location',
        ),
    ]
