# Generated by Django 5.2.1 on 2025-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0006_rename_town_ward_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
