# Generated by Django 5.2.1 on 2025-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0007_ward_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
