# Generated by Django 5.2.1 on 2025-07-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ward", "0008_alter_ward_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ward",
            old_name="location",
            new_name="address",
        ),
    ]
