# Generated by Django 5.2.1 on 2025-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_user", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("ward", "Ward")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
