# Generated by Django 5.2.1 on 2025-07-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_user", "0005_user_role_alter_userprofile_address_and_more"),
        ("ward", "0002_alter_ward_area_boundary_alter_ward_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ward",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="ward.ward",
            ),
        ),
    ]
