# Generated by Django 5.2.1 on 2025-11-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_user", "0007_alter_userprofile_user"),
        ("ward", "0009_rename_location_ward_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="ward.ward",
            ),
        ),
    ]
