# Generated by Django 5.2.1 on 2025-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholereport",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="report/"),
        ),
    ]
