# Generated by Django 5.2.1 on 2025-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_potholereport_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholereport",
            name="priority",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("approved", "Approved"),
                    ("spam", "Spam"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
