# Generated by Django 5.2.1 on 2025-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_potholereport_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potholereport",
            name="priority",
            field=models.CharField(
                choices=[("low", "low"), ("medium", "medium"), ("high", "High")],
                default="low",
                max_length=20,
            ),
        ),
    ]
