# Generated by Django 5.2.1 on 2025-07-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_rename_priority_potholereport_severity"),
        ("ward", "0005_alter_ward_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholereport",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="ward.ward",
            ),
        ),
    ]
