# Generated by Django 5.2.1 on 2025-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_potholereport_ward"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholereport",
            name="system_flag",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("needs_review", "Needs Review"),
                    ("suspicious", "Suspicious"),
                    ("invalid", "Invalid"),
                ],
                default="needs_review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in progress", "In Progress"),
                    ("partially_resolved", "Partially Resolved"),
                    ("resolved", "Resolved"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
