# Generated by Django 5.2.1 on 2025-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_potholereport_system_flag_alter_potholereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='system_flag',
            field=models.CharField(choices=[('valid', 'Valid'), ('needs_review', 'Needs Review'), ('suspicious', 'Suspicious'), ('invalid', 'Invalid')], default='valid', max_length=20),
        ),
    ]
