# Generated by Django 5.2.1 on 2025-07-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_potholereport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholereport',
            name='system_flag',
            field=models.CharField(choices=[('valid', 'Valid'), ('needs_review', 'Needs Review'), ('invalid', 'Invalid')], default='valid', max_length=20),
        ),
    ]
