# Generated by Django 5.2.1 on 2025-06-11 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ward", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("center_longitude", models.FloatField()),
                ("center_latitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in progress", "In Progress"),
                            ("partially_resolved", "Partially Resolved"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(blank=True, null=True)),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clusters",
                        to="ward.ward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
