# Generated by Django 5.2.1 on 2025-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="title",
            field=models.CharField(blank=True, null=True),
        ),
    ]
