# Generated by Django 5.2.1 on 2025-07-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0002_cluster_title"),
        ("ward", "0002_alter_ward_area_boundary_alter_ward_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="ward",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clusters",
                to="ward.ward",
            ),
        ),
    ]
