# Generated by Django 5.2.1 on 2025-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0003_alter_cluster_ward"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="priority_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cluster",
            name="system_flag",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("needs_review", "Needs Review"),
                    ("suspicious", "Suspicious"),
                    ("invalid", "Invalid"),
                ],
                default="needs_review",
                max_length=40,
            ),
        ),
    ]
