# Generated by Django 5.2.1 on 2025-07-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0004_cluster_priority_cluster_priority_score_and_more"),
        ("ward", "0005_alter_ward_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clusters",
                to="ward.ward",
            ),
        ),
    ]
