# Generated by Django 5.2.1 on 2025-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_alter_cluster_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('partially_resolved', 'Partially Resolved'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
